# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3.8' # Specifies the version of the Docker Compose file format

# This is the main section where we define all our services (containers)
services:
  # Define our .NET API service
  api:
    container_name: assetgaze-api # A friendly name for our API container
    build:
      context: . # The build context is the current directory (the project root)
      dockerfile: src/Assetgaze.Transactions.API/Dockerfile # The path to the Dockerfile we created
    ports:
      # Maps port 8080 inside the container to port 5001 on your Mac.
      # Format is "HOST:CONTAINER"
      - "5001:8080"
      # --- ADD A NEW PORT MAPPING FOR HTTPS ---
      # We'll map port 8081 inside the container to port 5002 on your Mac
      - "5002:8081"
    environment:
      # Environment variables passed to our API service
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # --- MODIFY THE URLS TO INCLUDE HTTPS ---
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      # --- ADD THESE ENVIRONMENT VARIABLES FOR KESTREL (the .NET web server) ---
      - Kestrel__Certificates__Default__Path=/https/assetgaze.pfx
      - Kestrel__Certificates__Default__Password=password # Use the same password as above
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=assetgazedb;Username=assetgazeuser;Password=yoursecurepassword
      # --- ADD A VOLUME TO MOUNT THE CERTIFICATE ---
    volumes:
        - ~/.aspnet/https/assetgaze.pfx:/https/assetgaze.pfx:ro # Mount as read-only
    depends_on:
      db:
        condition: service_healthy # Wait for the healthcheck to pass

  # Define our PostgreSQL database service
  db:
    container_name: assetgaze-db # A friendly name for our database container
    image: postgres:16-alpine # Use the official PostgreSQL 16 image from Docker Hub
    environment:
      # These variables are used by the postgres image to initialize the database
      - POSTGRES_DB=assetgazedb
      - POSTGRES_USER=assetgazeuser
      - POSTGRES_PASSWORD=yoursecurepassword
    ports:
      # Maps port 5432 inside the container to port 5432 on your Mac, so you can connect with a DB tool if needed.
      - "5432:5432"
    volumes:
      # This creates a persistent volume. The data in your database will be saved here,
      # so it will still be there even if you stop and restart the container.
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # This command checks if the postgres user can connect to the database
      test: [ "CMD-SHELL", "pg_isready -U assetgazeuser -d assetgazedb" ]
      interval: 5s   # Check every 5 seconds
      timeout: 5s    # Wait up to 5 seconds for the command to respond
      retries: 5     # Try up to 5 times before marking as unhealthy

# This section defines the named volumes used by our services
volumes:
  postgres_data: